### ISSUE TITLE
Unable to install plugin 

### ISSUE THREAD

**Issue by karnamonkster** [logstash-plugins/logstash-input-rss#4]
Hi,

With the configuration Logstash version : logstash-1.5.0.beta1
I am trying to build the plugin as per the README "section 2.2 Run in an installed Logstash" but facing issues.
$ bundle install
There was a NoMethodError while loading logstash-input-rss.gemspec: 
undefined method `metadata=' for #<Gem::Specification name=logstash-input-rss version=0.1.2> from
  /path_to_logstash/logstash-1.5.0.beta1/logstash-input-rss/logstash-input-rss.gemspec:20:in `block in<main>'

Also when run : 
$ gem build logstash-input-rss.gemspec
Invalid gemspec in [logstash-input-rss.gemspec]: undefined method `metadata=' for #<Gem::Specification name=logstash-input-rss version=0.1.2>
ERROR:  Error loading gemspec. Aborting.

Please help

**Comment by wiibaa** [comment]
@karnamonkster can you please check your ruby version, Logstash required min 1.9.
I tested myself and built successfully with jruby 1.7.17 and mri 2.0 on windows

**Comment by electrical** [comment]
@karnamonkster can you `gem update --system`.
It seems your gem version is to old.

**Comment by karnamonkster** [comment]
Now i am trying to work with logstash 1.4.2 version and still facing the issue with rss input plugin.

gem version - 1.8.11
Ruby -ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
Can you tell me the next way forward

**Comment by karnamonkster** [comment]
Any updates on this one?

**Comment by javifr** [comment]
I'm facing  the same problem..
+1

**Comment by chrc** [comment]
Hello,

I'm facing the same problem..
+1

**Comment by javifr** [comment]
I ended adding my plugin on the Gemfile of Logstash, like this:
```
source "https://rubygems.org"
gemspec :name => "logstash-core"
gem "your-plugin", :path => "/path/to/your/plugin"
gem "logstash-output-zeromq"
...
```

Then running inside the logstash folder: 
```/bin/plugin install --no-verify```

Hope it helps...

**Comment by ptitloup** [comment]
hello,
exactly the same problem...

:/opt/logstash-1.5.0/logstash-input-LDAPSearch# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
There was a NoMethodError while loading logstash-input-LDAPSearch.gemspec: 
undefined method `metadata=' for #<Gem::Specification:0x7fb7e5253740> from
  /opt/logstash-1.5.0/logstash-input-LDAPSearch/logstash-input-LDAPSearch.gemspec:20

Can you help ?
+1

**Comment by ptitloup** [comment]
I found a solution to solve my problem and run bundle install. metadata appear only with ruby 2..
So to install it on debian, i used rvm.
- #gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- #curl -sSL https://get.rvm.io | bash -s stable --ruby
and after, to use it : 
#source /usr/local/rvm/scripts/rvm
#ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by jsvd** [comment]
the plugin's gemspec has been updated lately and on 1.5.0 it installs cleanly:

```
/tmp/logstash-1.5.0 % bin/plugin install logstash-input-rss
Validating logstash-input-rss
Installing logstash-input-rss
Installation successful
```
