### ISSUE TITLE
Continued Errors With Plugin

### ISSUE THREAD

**Issue by dray0n** [logstash-plugins/logstash-input-rss#13]
Hello,

I have tried searching for a solution from these errors but I have been unable to.  I have tried on 2 servers.

1. Fresh install of Ubuntu 15.10 Server -- Also fresh 14.04.03
2. Install of Logstash Only 
3. Using StdOut to see reporting

I have been trying to ingest some security blogs and have continued to receive this error.
```
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss interval=>300, url=>"http://www.symantec.com/connect/feeds/srblog-external", codec=><LogStash::Codecs::Plain charset=>"UTF-8">>
  Error: undefined local variable or method `queue' for #<LogStash::Inputs::Rss:0x11cdfc78> {:level=>:error}
```

I would appreciate any guidance on finding a solution.

Thank you!

**Comment by inqueue** [comment]
Which Logstash version @dray0n? I am seeing the same with 2.1.1 and 2.1.0. It worked fine with 1.5.4.
